spring:
  kafka:
    bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
    properties:
      security:
        protocol: SASL_SSL
        sasl:
          mechanism: SCRAM-SHA-256
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
    consumer:
      group-id: ${CLOUDKARAFKA_USERNAME}-consumers
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
    producer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

cloudkarafka:
  topic: ${CLOUDKARAFKA_USERNAME}-default